In [1]:
import pandas as pd
import numpy as np

In [2]:
df_store=pd.read_csv("/content/stores_data_set.csv")
df_store.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [3]:
df_store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [10]:
df_sales=pd.read_csv("/content/sales_data_set.csv")
df_sales

        Store  Dept        Date  Weekly_Sales  IsHoliday
0           1     1  05/02/2010      24924.50      False
1           1     1  12/02/2010      46039.49       True
2           1     1  19/02/2010      41595.55      False
3           1     1  26/02/2010      19403.54      False
4           1     1  05/03/2010      21827.90      False
...       ...   ...         ...           ...        ...
421565     45    98  28/09/2012        508.37      False
421566     45    98  05/10/2012        628.10      False
421567     45    98  12/10/2012       1061.02      False
421568     45    98  19/10/2012        760.01      False
421569     45    98  26/10/2012       1076.80      False

[421570 rows x 5 columns]

In [11]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB

In [12]:
df_sales.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [13]:
df_sales['Date']=pd.to_datetime(df_sales['Date'], format= '%d/%m/%Y')

In [4]:
df_features=pd.read_csv("/content/Features_data_set.csv")
df_features

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8185,45,28/06/2013,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,False
8186,45,05/07/2013,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,False
8187,45,12/07/2013,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,False
8188,45,19/07/2013,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,False
8189,45,26/07/2013,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,False

In [5]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

In [6]:
df_features.isnull().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [7]:
df_features['Date']=pd.to_datetime(df_features['Date'], format= '%d/%m/%Y')

In [8]:
df_features.MarkDown1.fillna(0,inplace = True)
df_features.MarkDown2.fillna(0,inplace = True)
df_features.MarkDown3.fillna(0,inplace = True)
df_features.MarkDown4.fillna(0,inplace = True)
df_features.MarkDown5.fillna(0,inplace = True)

In [9]:
df_features.isnull().sum()

Store             0
Date              0
Temperature       0
Fuel_Price        0
MarkDown1         0
MarkDown2         0
MarkDown3         0
MarkDown4         0
MarkDown5         0
CPI             585
Unemployment    585
IsHoliday         0
dtype: int64

In [14]:
df1=pd.merge(df_features, df_sales, on=['Store', 'Date'])
df1

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y
0,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,1,24924.50,False
1,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,2,50605.27,False
2,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,3,13740.12,False
3,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,4,39954.04,False
4,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,5,32229.38,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False
421566,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False
421567,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False
421568,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False
421569,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False

In [16]:
df2= pd.merge(df1, df_store, on=['Store'])
df2

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y,Type,Size
0,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,1,24924.50,False,A,151315
1,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,2,50605.27,False,A,151315
2,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,3,13740.12,False,A,151315
3,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,4,39954.04,False,A,151315
4,1,2010-02-05,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,5,32229.38,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False,B,118221
421566,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False,B,118221
421567,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False,B,118221
421568,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False,B,118221
421569,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False,B,118221

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Date          421570 non-null  datetime64[ns]
 2   Temperature   421570 non-null  float64
 3   Fuel_Price    421570 non-null  float64
 4   MarkDown1     421570 non-null  float64
 5   MarkDown2     421570 non-null  float64
 6   MarkDown3     421570 non-null  float64
 7   MarkDown4     421570 non-null  float64
 8   MarkDown5     421570 non-null  float64
 9   CPI           421570 non-null  float64
 10  Unemployment  421570 non-null  float64
 11  IsHoliday_x   421570 non-null  bool
 12  Dept          421570 non-null  int64
 13  Weekly_Sales  421570 non-null  float64
 14  IsHoliday_y   421570 non-null  bool
 15  Type          421570 non-null  object
 16  Size          421570 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(10), int64(3), object(1)
memory usage: 49.0+ MB

In [ ]:
# df3=pd.merge(df_store, df_features, on = 'Store', how= 'outer')
# df3=pd.merge(df3, df_sales, on= 'Store', how= 'outer')

In [ ]:
# Query
● Which store performs high sales in week wise
● Identify average customer visit in the type B store in April Months

● Identify best average sales in holiday week for all store types

● Which store had a worst sales in leap year

● What is the expected sales of each department when unemployment factor is greater>8

● Aggregate the net(total) sales of each department on month wise


*   List item
*   List item


● Identify better department performance based on the store on all the week

● Identify the store which has minimum fuel price based on the week

● Identify overall performance of the store based on year wise

● Identify the performance of the store on week wise with without offers

In [17]:
#Which store performs high sales in week wise
df_sales['Week']=df_sales['Date'].dt.strftime('%U')
df_sales['Week']

0         05
1         06
2         07
3         08
4         09
          ..
421565    39
421566    40
421567    41
421568    42
421569    43
Name: Week, Length: 421570, dtype: object

In [18]:
weekly_sales_by_store = df_sales.groupby(['Store', 'Week'])['Weekly_Sales'].sum().reset_index()
weekly_sales_by_store

      Store Week  Weekly_Sales
0         1   01    2995102.20
1         1   02    2850615.13
2         1   03    2721799.26
3         1   04    2636224.90
4         1   05    4886660.13
...     ...  ...           ...
2335     45   48    1754944.71
2336     45   49    1959519.65
2337     45   50    2202188.53
2338     45   51    3204820.02
2339     45   52    1548559.83

[2340 rows x 3 columns]

In [19]:
weekly_sales_by_store.loc[weekly_sales_by_store.groupby('Week')['Weekly_Sales'].idxmax()]

      Store Week  Weekly_Sales
156       4   01    3910242.34
157       4   02    3807179.07
158       4   03    3891491.70
159       4   04    3742961.36
992      20   05    6956061.74
993      20   06    6783474.32
162       4   07    6793995.99
163       4   08    6230485.70
996      20   09    6411461.09
997      20   10    6141173.01
166       4   11    6228872.18
687      14   12    5823295.21
1000     20   13    6408110.05
689      14   14    6672602.42
1002     20   15    6088586.98
691      14   16    6270292.74
692      14   17    5797002.71
693      14   18    6415070.74
1006     20   19    6238057.26
175       4   20    6126530.89
696      14   21    6338716.01
1009     20   22    6528992.63
698      14   23    6481631.92
1011     20   24    6322255.19
648      13   25    6073876.33
1013     20   26    6252794.79
1014     20   27    6589128.94
1015     20   28    6206408.03
184       4   29    6060221.86
185       4   30    5834925.33
186       4   31    6242210.10
187       4   32    6306087.18
188       4   33    6513613.49
657      13   34    6002981.06
1022     20   35    6325808.95
711      14   36    6299023.00
192       4   37    6093391.54
193       4   38    5961529.62
1026     20   39    5887878.05
1027     20   40    6442783.95
1028     20   41    6123735.43
197       4   42    6232619.04
198       4   43    6234587.05
1031     20   44    4468423.24
1032     20   45    4457741.13
201       4   46    4341755.99
514      10   47    5890145.02
1035     20   48    4714828.00
1036     20   49    5298245.86
1037     20   50    5582009.82
1038     20   51    7322058.46
1039     20   52    3842982.79

In [20]:
# Extracting week from the 'Date' column
df_sales['Week'] = df_sales['Date'].dt.strftime('%U')

# Grouping by store and week, then calculating the sum of weekly sales
weekly_sales_by_store = df_sales.groupby(['Store', 'Week'])['Weekly_Sales'].sum().reset_index()

# Finding the store with the highest weekly sales
store_with_highest_sales = weekly_sales_by_store.loc[weekly_sales_by_store.groupby('Week')['Weekly_Sales'].idxmax()].reset_index()

# Displaying the store with the highest sales in each week
print(store_with_highest_sales)

    index  Store Week  Weekly_Sales
0     156      4   01    3910242.34
1     157      4   02    3807179.07
2     158      4   03    3891491.70
3     159      4   04    3742961.36
4     992     20   05    6956061.74
5     993     20   06    6783474.32
6     162      4   07    6793995.99
7     163      4   08    6230485.70
8     996     20   09    6411461.09
9     997     20   10    6141173.01
10    166      4   11    6228872.18
11    687     14   12    5823295.21
12   1000     20   13    6408110.05
13    689     14   14    6672602.42
14   1002     20   15    6088586.98
15    691     14   16    6270292.74
16    692     14   17    5797002.71
17    693     14   18    6415070.74
18   1006     20   19    6238057.26
19    175      4   20    6126530.89
20    696     14   21    6338716.01
21   1009     20   22    6528992.63
22    698     14   23    6481631.92
23   1011     20   24    6322255.19
24    648     13   25    6073876.33
25   1013     20   26    6252794.79
26   1014     20   27    6589128.94
27   1015     20   28    6206408.03
28    184      4   29    6060221.86
29    185      4   30    5834925.33
30    186      4   31    6242210.10
31    187      4   32    6306087.18
32    188      4   33    6513613.49
33    657     13   34    6002981.06
34   1022     20   35    6325808.95
35    711     14   36    6299023.00
36    192      4   37    6093391.54
37    193      4   38    5961529.62
38   1026     20   39    5887878.05
39   1027     20   40    6442783.95
40   1028     20   41    6123735.43
41    197      4   42    6232619.04
42    198      4   43    6234587.05
43   1031     20   44    4468423.24
44   1032     20   45    4457741.13
45    201      4   46    4341755.99
46    514     10   47    5890145.02
47   1035     20   48    4714828.00
48   1036     20   49    5298245.86
49   1037     20   50    5582009.82
50   1038     20   51    7322058.46
51   1039     20   52    3842982.79

In [21]:
# Identify average customer visit in the type B store in April Months

df_store[df_store['Type'] == 'B']

    Store Type    Size
2       3    B   37392
4       5    B   34875
6       7    B   70713
8       9    B  125833
9      10    B  126512
11     12    B  112238
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
20     21    B  140167
21     22    B  119557
22     23    B  114533
24     25    B  128107
28     29    B   93638
34     35    B  103681
44     45    B  118221

In [22]:
type_b_stores_sales = df_sales[df_sales['Store'].isin(df_store[df_store['Type'] == 'B']['Store'])]
type_b_stores_sales

        Store  Dept       Date  Weekly_Sales  IsHoliday Week
20482       3     1 2010-02-05       6453.58      False   05
20483       3     1 2010-02-12      12748.72       True   06
20484       3     1 2010-02-19       8918.31      False   07
20485       3     1 2010-02-26       4992.00      False   08
20486       3     1 2010-03-05       5172.73      False   09
...       ...   ...        ...           ...        ...  ...
421565     45    98 2012-09-28        508.37      False   39
421566     45    98 2012-10-05        628.10      False   40
421567     45    98 2012-10-12       1061.02      False   41
421568     45    98 2012-10-19        760.01      False   42
421569     45    98 2012-10-26       1076.80      False   43

[163495 rows x 6 columns]

In [23]:
# Filter sales data for Type B stores
type_b_stores_sales = df_sales[df_sales['Store'].isin(df_store[df_store['Type'] == 'B']['Store'])]

# Filter sales data for April
april_sales = type_b_stores_sales[(type_b_stores_sales['Date'].dt.month == 4)]

# Calculate the average customer visit
average_customer_visit = april_sales.groupby('Store')['Date'].nunique().mean()

print("Average customer visit in Type B stores in April:", average_customer_visit)

Average customer visit in Type B stores in April: 14.0

In [ ]:
# Identify best average sales in holiday week for all store types

In [24]:
# Filter sales data for holiday weeks
holiday_sales = df_sales[df_sales['IsHoliday']]

# Calculate total sales for each store during holiday weeks
total_sales_by_store = holiday_sales.groupby('Store')['Weekly_Sales'].sum()

# Merge total sales with store type
merged_sales = total_sales_by_store.reset_index().merge(df_store, on='Store')

# Calculate average sales for each store type during holiday weeks
average_sales_by_type = merged_sales.groupby('Type')['Weekly_Sales'].mean()

# Identify store type with the highest average sales during holiday weeks
best_store_type = average_sales_by_type.idxmax()
best_average_sales = average_sales_by_type.max()

print("Best average sales in holiday week for all store types:", best_store_type)
print("Average sales value:", best_average_sales)

Best average sales in holiday week for all store types: A
Average sales value: 14700127.643636364

In [25]:
# Which store had a worst sales in leap year

# Assuming df_sales contains the sales data
# First, convert the 'Date' column to datetime if it's not already
df_sales['Date'] = pd.to_datetime(df_sales['Date'])

# Filter sales data for the leap year
leap_year_sales = df_sales[df_sales['Date'].dt.year % 4 == 0]

# Calculate total sales for each store during the leap year
total_sales_by_store = leap_year_sales.groupby('Store')['Weekly_Sales'].sum()

# Find the store with the minimum total sales
worst_store = total_sales_by_store.idxmin()
worst_sales = total_sales_by_store.min()

print("Store with the worst sales in the leap year:", worst_store)
print("Total sales:", worst_sales)

Store with the worst sales in the leap year: 33
Total sales: 11435551.03

In [26]:
# What is the expected sales of each department when unemployment factor is greater>8

# Assuming df_sales contains the sales data
# Assuming df_features contains the features data including unemployment factor

# Merge sales data with features data on the 'Store' and 'Date' columns
merged_data = pd.merge(df_sales, df_features, on=['Store', 'Date'])

# Filter data where unemployment factor is greater than 8
high_unemployment_sales = merged_data[merged_data['Unemployment'] > 8]

# Calculate average sales for each department
average_sales_by_department = high_unemployment_sales.groupby('Dept')['Weekly_Sales'].mean()

print("Expected sales of each department when unemployment factor is greater than 8:")
print(average_sales_by_department)

Expected sales of each department when unemployment factor is greater than 8:
Dept
1     17719.577853
2     43370.044649
3     10984.784400
4     25040.236272
5     19914.917085
          ...
95    68200.568373
96    15487.837565
97    13024.744137
98     6225.629719
99      342.380187
Name: Weekly_Sales, Length: 81, dtype: float64

In [27]:
# Aggregate the net(total) sales of each department on month wise

# Assuming df_sales contains the sales data
# Assuming the 'Date' column is already in datetime format

# Extract month from the 'Date' column
df_sales['Month'] = df_sales['Date'].dt.month

# Group by department and month, then calculate the sum of weekly sales
monthly_sales_by_department = df_sales.groupby(['Dept', 'Month'])['Weekly_Sales'].sum().reset_index()

print("Net (total) sales of each department on month-wise basis:")
print(monthly_sales_by_department)

Net (total) sales of each department on month-wise basis:
     Dept  Month  Weekly_Sales
0       1      1    4919530.75
1       1      2   12657329.37
2       1      3   10809758.44
3       1      4   17620651.88
4       1      5    7650736.26
..    ...    ...           ...
957    99      8      18816.56
958    99      9       4878.76
959    99     10      13665.09
960    99     11      78254.54
961    99     12     152432.68

[962 rows x 3 columns]

In [28]:
# Identify better department performance based on the store on all the week

# Group by store and department, then calculate the sum of weekly sales
total_sales_by_store_department = df_sales.groupby(['Store', 'Dept'])['Weekly_Sales'].sum().reset_index()

# Find the department with the highest total sales for each store
best_department_by_store = total_sales_by_store_department.loc[total_sales_by_store_department.groupby('Store')['Weekly_Sales'].idxmax()]

print("Department performance based on the store across all weeks:")
print(best_department_by_store)

Department performance based on the store across all weeks:
      Store  Dept  Weekly_Sales
69        1    92   19370632.64
147       2    92   23572153.03
190       3    38   15529566.07
297       4    92   22789210.43
340       5    38    7893570.24
446       6    92   14160545.90
509       7    72    6447844.96
601       8    95    9002059.31
641       9    38   11184287.78
736      10    72   20410926.56
829      11    95   11080680.91
835      12     2   10652763.01
980      13    92   23170876.20
1057     14    92   26101497.71
1101     15    38    7517821.66
1179     16    38    7447254.23
1255     17    38   11059588.03
1331     18    38    9339684.03
1445     19    92   16261990.45
1523     20    92   23542625.04
1532     21     2    6832625.68
1643     22    38   10015536.66
1740     23    72   10988695.25
1830     24    92   17429136.57
1874     25    38    6381753.99
1950     26    38   14800243.10
2061     27    92   20952094.22
2138     28    92   14083635.33
2181     29    38    6075233.36
2255     30    38    8761108.01
2355     31    92   18162446.96
2432     32    92   14317578.85
2495     33    92    4894555.79
2576     34    95    9902061.88
2635     35    72   12631448.67
2712     36    94    6774217.61
2747     37    38    9922606.19
2812     38    38    7858677.16
2910     39    92   15748047.97
2987     40    92   13796032.72
3064     41    92   16563355.96
3127     42    92   11940182.35
3187     43    92   11961401.01
3225     44    38    6546336.18
3292     45    38    7613685.44

In [29]:
# Identify the store which has minimum fuel price based on the week

# Group by week and store, then find the record with the minimum fuel price in each week
min_fuel_price_by_store_week = df_features.groupby(['Date', 'Store'])['Fuel_Price'].min().reset_index()

# Find the store with the minimum fuel price based on the week
store_with_min_fuel_price = min_fuel_price_by_store_week.loc[min_fuel_price_by_store_week.groupby('Date')['Fuel_Price'].idxmin()]

print("Store with the minimum fuel price based on the week:")
print(store_with_min_fuel_price)

Store with the minimum fuel price based on the week:
           Date  Store  Fuel_Price
35   2010-02-05     36       2.545
80   2010-02-12     36       2.539
125  2010-02-19     36       2.472
170  2010-02-26     36       2.520
215  2010-03-05     36       2.574
...         ...    ...         ...
8000 2013-06-28     36       3.428
8013 2013-07-05      4       3.385
8058 2013-07-12      4       3.368
8135 2013-07-19     36       3.507
8148 2013-07-26      4       3.580

[182 rows x 3 columns]

In [30]:
# Identify overall performance of the store based on year wise

# Assuming df_sales contains the sales data
# Assuming the 'Date' column is already in datetime format

# Extract year from the 'Date' column
df_sales['Year'] = df_sales['Date'].dt.year

# Group by store and year, then calculate the sum of weekly sales
total_sales_by_store_year = df_sales.groupby(['Store', 'Year'])['Weekly_Sales'].sum().reset_index()

# Find the overall performance of each store based on year wise
overall_performance_by_store = total_sales_by_store_year.groupby('Store')['Weekly_Sales'].sum()

print("Overall performance of each store based on year wise:")
print(overall_performance_by_store)

Overall performance of each store based on year wise:
Store
1     2.224028e+08
2     2.753824e+08
3     5.758674e+07
4     2.995440e+08
5     4.547569e+07
6     2.237561e+08
7     8.159828e+07
8     1.299512e+08
9     7.778922e+07
10    2.716177e+08
11    1.939628e+08
12    1.442872e+08
13    2.865177e+08
14    2.889999e+08
15    8.913368e+07
16    7.425243e+07
17    1.277821e+08
18    1.551147e+08
19    2.066349e+08
20    3.013978e+08
21    1.081179e+08
22    1.470756e+08
23    1.987506e+08
24    1.940160e+08
25    1.010612e+08
26    1.434164e+08
27    2.538559e+08
28    1.892637e+08
29    7.714155e+07
30    6.271689e+07
31    1.996139e+08
32    1.668192e+08
33    3.716022e+07
34    1.382498e+08
35    1.315207e+08
36    5.341221e+07
37    7.420274e+07
38    5.515963e+07
39    2.074455e+08
40    1.378703e+08
41    1.813419e+08
42    7.956575e+07
43    9.056544e+07
44    4.329309e+07
45    1.123953e+08
Name: Weekly_Sales, dtype: float64

In [31]:
# Identify the performance of the store on week wise with without offers

# Merge sales data with features data on the 'Date' column
merged_data = pd.merge(df_sales, df_features, on='Date')

# Assuming 'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5' represent offers, check if any of them are not NaN
merged_data['Offers_Present'] = ~merged_data[['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']].isna().any(axis=1)

# Group by week and whether offers were present or not, then calculate the sum of weekly sales
performance_by_week_with_offers = merged_data.groupby(['Date', 'Offers_Present'])['Weekly_Sales'].sum().reset_index()

print("Performance of the store on week-wise basis with and without offers:")
print(performance_by_week_with_offers)

Performance of the store on week-wise basis with and without offers:
          Date  Offers_Present  Weekly_Sales
0   2010-02-05            True  2.238783e+09
1   2010-02-12            True  2.175150e+09
2   2010-02-19            True  2.172465e+09
3   2010-02-26            True  1.978586e+09
4   2010-03-05            True  2.109216e+09
..         ...             ...           ...
138 2012-09-28            True  1.968070e+09
139 2012-10-05            True  2.140499e+09
140 2012-10-12            True  2.075783e+09
141 2012-10-19            True  2.030508e+09
142 2012-10-26            True  2.049485e+09

[143 rows x 3 columns]